/* Auto-generated by tools/extract_trig_tables.py — do not edit. */
#pragma once
#include <stdint.h>

/* 512-step trig region (CPU $92FC00-$9307FE, bank1 file $12FC00-$1307FE)  */
/* g_trig_512[0..511]   = cos data  (CPU $92FC00-$92FFFE, base-$400..base) */
/* g_trig_512[512]      = CPU $930000 base (not directly accessed)          */
/* g_trig_512[513..1023]= sin data  (CPU $930002-$930400, base+$2..+$400)  */
/* g_trig_512[1024..1535]=sin_neg   (CPU $930402-$9307FE, base+$402..+$800)*/
/* atan2_tbl1 base: &g_trig_512[769]  (CPU $930202 = base+$202)            */
/* atan2_tbl2 base: &g_trig_512[1025] (CPU $930402 = base+$402)            */
extern const int16_t g_trig_512[1536];

/* angle_to_sine tables ($93A02C / $93A42C). 512 entries, accessed via     */
/* byte_offset = (angle_diff * 2) & 0x03FF (even offsets 0..$3FE).         */
extern const int16_t g_sin_512[512];
extern const int16_t g_cos_512[512];

/* Accessors matching original 68K table access logic exactly.             */

/* sin_lookup(angle 0-511): offset = (512-angle)*2 from CPU $930000 base  */
static inline int16_t trig_sin_512(uint16_t angle) {
    return g_trig_512[1024u - angle];
}

/* cos_lookup(angle 0-511): offset = (angle-512)*2 from base, negate      */
static inline int16_t trig_cos_512(uint16_t angle) {
    return -(int16_t)g_trig_512[angle];
}

/* sin_neg_lookup(angle 0-1023): offset=(1024-angle)*2, negate result     */
static inline int16_t trig_sin_neg_512(uint16_t angle) {
    return -(int16_t)g_trig_512[1536u - angle];
}

/* angle_to_sine lookups — handle negative angles with odd symmetry.       */
/* Original: byte_off = (angle*2) & 0x03FF; word_idx = byte_off/2         */
/*         = angle & 0x01FF  (low 9 bits of angle)                        */
static inline int16_t trig_angle_sin(int16_t angle) {
    if (angle >= 0) return  g_sin_512[(uint16_t)angle  & 0x01FFu];
    else            return -g_sin_512[(uint16_t)-angle & 0x01FFu];
}
static inline int16_t trig_angle_cos(int16_t angle) {
    if (angle >= 0) return  g_cos_512[(uint16_t)angle  & 0x01FFu];
    else            return -g_cos_512[(uint16_t)-angle & 0x01FFu];
}