#!/bin/bash
# Convert SH2 assembly to dc.w include file
# Usage: ./asm_to_dcw.sh <input.asm> <output.inc>

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <input.asm> <output.inc>"
    echo "Example: $0 disasm/sh2/slave_comm2_test.asm disasm/sh2/generated/slave_comm2_test.inc"
    exit 1
fi

INPUT_ASM="$1"
OUTPUT_INC="$2"

BASENAME=$(basename "$INPUT_ASM" .asm)
TMP_OBJ="/tmp/${BASENAME}.o"
TMP_BIN="/tmp/${BASENAME}.bin"

# Create output directory
mkdir -p "$(dirname "$OUTPUT_INC")"

echo "==================================================================="
echo "SH2 Assembly → dc.w Converter"
echo "==================================================================="
echo "Input:  $INPUT_ASM"
echo "Output: $OUTPUT_INC"
echo ""

# Step 1: Assemble
echo "[1/3] Assembling with sh-elf-as..."
if ! sh-elf-as --isa=sh2 -o "$TMP_OBJ" "$INPUT_ASM" 2>&1; then
    echo "ERROR: Assembly failed"
    exit 1
fi
echo "      ✓ Assembled to object file"

# Step 2: Extract binary
echo "[2/3] Extracting binary..."
if ! sh-elf-objcopy -O binary "$TMP_OBJ" "$TMP_BIN"; then
    echo "ERROR: Binary extraction failed"
    exit 1
fi
SIZE=$(stat -c%s "$TMP_BIN" 2>/dev/null || stat -f%z "$TMP_BIN")
echo "      ✓ Extracted $SIZE bytes"

# Step 3: Convert to dc.w format
echo "[3/3] Converting to dc.w format..."
cat > "$OUTPUT_INC" <<EOF
; Auto-generated from: $INPUT_ASM
; Generated: $(date)
; Size: $SIZE bytes ($((SIZE/2)) words)
;
; DO NOT EDIT THIS FILE MANUALLY
; Edit the source assembly file and regenerate with:
;   tools/asm_to_dcw.sh $INPUT_ASM $OUTPUT_INC
;
EOF

# Convert binary to dc.w format (big-endian)
xxd -p -c2 "$TMP_BIN" | awk '{
    word = toupper($1)
    if (NR == 1) {
        printf "        dc.w    $%s", word
    } else {
        if ((NR - 1) % 8 == 0) {
            printf "\n        dc.w    $%s", word
        } else {
            printf ", $%s", word
        }
    }
}
END {
    printf "\n"
}' >> "$OUTPUT_INC"

echo "      ✓ Converted to dc.w format"

# Show preview
echo ""
echo "==================================================================="
echo "✓ Conversion complete!"
echo "==================================================================="
echo ""
echo "Preview of $OUTPUT_INC:"
echo "-------------------------------------------------------------------"
head -15 "$OUTPUT_INC"
echo "..."
echo "-------------------------------------------------------------------"
echo ""
echo "Binary output:"
hexdump -C "$TMP_BIN" | head -3
echo ""
echo "Include in your section file with:"
echo "  include \"$(echo "$OUTPUT_INC" | sed 's|^disasm/||')\""
echo ""
