#!/usr/bin/env python3
"""Extract VRD palette data from the 32X ROM and emit Saturn C source files."""

import struct
import os

ROM_PATH = os.path.join(os.path.dirname(__file__), "..", "Virtua Racing Deluxe (USA).32x")
OUT_C    = os.path.join(os.path.dirname(__file__), "..", "saturn", "src", "render", "vrd_palette.c")
OUT_H    = os.path.join(os.path.dirname(__file__), "..", "saturn", "src", "render", "vrd_palette.h")

# 68K address → file offset
def cpu_to_file(addr):
    return addr - 0x880000

PALETTE_COUNT   = 3
PALETTE_ENTRIES = 128

# Palette pointer table at $0088EACE (file 0x0EACE)
PTR_TABLE_OFFSET = 0x0EACE

def read_palette(rom, file_offset):
    entries = []
    for i in range(PALETTE_ENTRIES):
        word, = struct.unpack_from(">H", rom, file_offset + i * 2)
        entries.append(word)
    return entries

def main():
    with open(ROM_PATH, "rb") as f:
        rom = f.read()

    # Read the 3 palette pointers
    palettes = []
    for i in range(PALETTE_COUNT):
        ptr_off = PTR_TABLE_OFFSET + i * 4
        cpu_addr, = struct.unpack_from(">I", rom, ptr_off)
        file_off = cpu_to_file(cpu_addr)
        print(f"  palette[{i}]: cpu=${cpu_addr:08X}  file=0x{file_off:05X}")
        palettes.append(read_palette(rom, file_off))

    # Emit .h
    h_lines = [
        "/* render/vrd_palette.h — VRD palette data extracted from 32X ROM. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define VRD_PALETTE_COUNT   3",
        "#define VRD_PALETTE_ENTRIES 128",
        "",
        "extern const uint16_t g_vrd_palette[VRD_PALETTE_COUNT][VRD_PALETTE_ENTRIES];",
        "",
        "/* Named indices (same meaning across all 3 palettes) */",
        "#define VRD_PAL_GREY_DARK   7    /* ~#494949 */",
        "#define VRD_PAL_GREY_ROAD  14    /* ~#6B6B6B road surface */",
        "#define VRD_PAL_WHITE      32    /* #FFFFFF  */",
        "#define VRD_PAL_GRASS_DARK 70    /* dark grass tones */",
        "",
    ]
    with open(OUT_H, "w") as f:
        f.write("\n".join(h_lines))

    # Emit .c
    c_lines = [
        "/* render/vrd_palette.c — VRD palette data extracted from 32X ROM. */",
        "/* AUTO-GENERATED by tools/extract_palette.py — do not edit by hand. */",
        '#include "vrd_palette.h"',
        "",
        "const uint16_t g_vrd_palette[VRD_PALETTE_COUNT][VRD_PALETTE_ENTRIES] = {",
    ]
    for pi, pal in enumerate(palettes):
        c_lines.append(f"    {{  /* palette {pi} */")
        for row in range(0, PALETTE_ENTRIES, 8):
            chunk = pal[row:row+8]
            hex_vals = ", ".join(f"0x{v:04X}" for v in chunk)
            c_lines.append(f"        {hex_vals},")
        c_lines.append("    },")
    c_lines.append("};")
    c_lines.append("")

    with open(OUT_C, "w") as f:
        f.write("\n".join(c_lines))

    print(f"Wrote {OUT_H}")
    print(f"Wrote {OUT_C}")

if __name__ == "__main__":
    main()
