#!/usr/bin/env python3
"""
Extract trig lookup tables from the Virtua Racing Deluxe 32X ROM and emit
a C source file for use in the Saturn port.

Address mapping (bank 1 active after boot, set via MOVE.W #1,$A15104):
  68K CPU $900000-$9FFFFF → ROM file $100000-$1FFFFF
  Formula: file_offset = cpu_addr - 0x00800000

Tables extracted:

  g_trig_512[1536] — CPU $92FC00–$9307FE / file $12FC00–$1307FE
    Combined region covering all three 512-step functions.
    g_trig_512[0..511]    = cos_lookup data  (below CPU $930000 base)
    g_trig_512[512]       = CPU $930000 (base pointer for all three)
    g_trig_512[513..1023] = sin_lookup data  (above base, up to +$400)
    g_trig_512[1024..1535]= sin_neg data     (above base, +$402 to +$800)
    atan2 table1 base: g_trig_512 + 769  (CPU $930202 = base+$202)
    atan2 table2 base: g_trig_512 + 1025 (CPU $930402 = base+$402)

    Accessor index formulas (base = 512):
      sin_lookup(angle 0-511)    : g_trig_512[1024 - angle]  (result as-is)
      cos_lookup(angle 0-511)    : g_trig_512[angle]          (negate result)
      sin_neg_lookup(angle 0-1023): g_trig_512[1536 - angle]  (negate result)

  g_sin_512[512] — CPU $93A02C / file $13A02C
    Used by angle_to_sine (1024-step angle system, 512 stored entries).
    Accessed as: byte_offset = (angle_diff * 2) & 0x03FF → word at that offset.

  g_cos_512[512] — CPU $93A42C / file $13A42C
    Used by angle_to_sine (cosine counterpart to g_sin_512).
"""

import struct
import sys
import os

ROM_PATH = os.path.join(os.path.dirname(__file__), "..", "Virtua Racing Deluxe (USA).32x")
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "saturn", "src", "math", "trig_tables.c")
HDR_PATH = os.path.join(os.path.dirname(__file__), "..", "saturn", "src", "math", "trig_tables.h")

# Bank 1 is set at boot (MOVE.W #1, $A15104):
#   CPU $900000-$9FFFFF → ROM file $100000-$1FFFFF
#   file_offset = cpu_addr - 0x800000
CPU_TO_FILE = 0x00800000

TABLES = [
    # (name, cpu_addr, n_entries, description)
    # g_trig_512: starts 512 words BELOW the $930000 base to cover cos_lookup
    # (cos uses negative offsets from the base: CPU $92FC00 = $930000 - $400)
    ("g_trig_512",  0x0092FC00, 1536,
     "512-step trig region: cos (below base) + sin + sin_neg (above base)"),
    # angle_to_sine tables — 512 entries each (accessed via & 0x03FF byte mask)
    ("g_sin_512",   0x0093A02C, 512,
     "angle_to_sine sine table (1024-step angles, 512 stored entries)"),
    ("g_cos_512",   0x0093A42C, 512,
     "angle_to_sine cosine table (1024-step angles, 512 stored entries)"),
]

def extract_table(rom_data, cpu_addr, n_entries):
    offset = cpu_addr - CPU_TO_FILE
    end    = offset + n_entries * 2
    if end > len(rom_data):
        raise ValueError(f"Table at ${cpu_addr:08X} (file ${offset:06X}) "
                         f"extends beyond ROM ({len(rom_data)} bytes)")
    words = struct.unpack_from(f">{n_entries}h", rom_data, offset)
    return words

def emit_c(tables_data):
    lines = [
        "/* Auto-generated by tools/extract_trig_tables.py — do not edit. */",
        "/* Source: Virtua Racing Deluxe (USA).32x                        */",
        '#include "trig_tables.h"',
        "",
    ]
    for name, cpu_addr, n_entries, desc in TABLES:
        values = tables_data[name]
        lines.append(f"/* {desc} */")
        lines.append(f"/* CPU address ${cpu_addr:08X}, {n_entries} entries */")
        lines.append(f"const int16_t {name}[{n_entries}] = {{")
        row_size = 8
        for i in range(0, n_entries, row_size):
            chunk = values[i:i+row_size]
            row   = ", ".join(f"{v:6d}" for v in chunk)
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")
    return "\n".join(lines)

def emit_h(tables_data):
    lines = [
        "/* Auto-generated by tools/extract_trig_tables.py — do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "/* 512-step trig region (CPU $92FC00-$9307FE, bank1 file $12FC00-$1307FE)  */",
        "/* g_trig_512[0..511]   = cos data  (CPU $92FC00-$92FFFE, base-$400..base) */",
        "/* g_trig_512[512]      = CPU $930000 base (not directly accessed)          */",
        "/* g_trig_512[513..1023]= sin data  (CPU $930002-$930400, base+$2..+$400)  */",
        "/* g_trig_512[1024..1535]=sin_neg   (CPU $930402-$9307FE, base+$402..+$800)*/",
        "/* atan2_tbl1 base: &g_trig_512[769]  (CPU $930202 = base+$202)            */",
        "/* atan2_tbl2 base: &g_trig_512[1025] (CPU $930402 = base+$402)            */",
        "extern const int16_t g_trig_512[1536];",
        "",
        "/* angle_to_sine tables ($93A02C / $93A42C). 512 entries, accessed via     */",
        "/* byte_offset = (angle_diff * 2) & 0x03FF (even offsets 0..$3FE).         */",
        "extern const int16_t g_sin_512[512];",
        "extern const int16_t g_cos_512[512];",
        "",
        "/* Accessors matching original 68K table access logic exactly.             */",
        "",
        "/* sin_lookup(angle 0-511): offset = (512-angle)*2 from CPU $930000 base  */",
        "static inline int16_t trig_sin_512(uint16_t angle) {",
        "    return g_trig_512[1024u - angle];",
        "}",
        "",
        "/* cos_lookup(angle 0-511): offset = (angle-512)*2 from base, negate      */",
        "static inline int16_t trig_cos_512(uint16_t angle) {",
        "    return -(int16_t)g_trig_512[angle];",
        "}",
        "",
        "/* sin_neg_lookup(angle 0-1023): offset=(1024-angle)*2, negate result     */",
        "static inline int16_t trig_sin_neg_512(uint16_t angle) {",
        "    return -(int16_t)g_trig_512[1536u - angle];",
        "}",
        "",
        "/* angle_to_sine lookups — handle negative angles with odd symmetry.       */",
        "/* Original: byte_off = (angle*2) & 0x03FF; word_idx = byte_off/2         */",
        "/*         = angle & 0x01FF  (low 9 bits of angle)                        */",
        "static inline int16_t trig_angle_sin(int16_t angle) {",
        "    if (angle >= 0) return  g_sin_512[(uint16_t)angle  & 0x01FFu];",
        "    else            return -g_sin_512[(uint16_t)-angle & 0x01FFu];",
        "}",
        "static inline int16_t trig_angle_cos(int16_t angle) {",
        "    if (angle >= 0) return  g_cos_512[(uint16_t)angle  & 0x01FFu];",
        "    else            return -g_cos_512[(uint16_t)-angle & 0x01FFu];",
        "}",
    ]
    return "\n".join(lines)

def main():
    if not os.path.exists(ROM_PATH):
        print(f"ERROR: ROM not found at {ROM_PATH}", file=sys.stderr)
        sys.exit(1)

    with open(ROM_PATH, "rb") as f:
        rom = f.read()

    print(f"ROM size: {len(rom):,} bytes ({len(rom)//1024} KB)")

    tables_data = {}
    for name, cpu_addr, n_entries, desc in TABLES:
        file_off = cpu_addr - CPU_TO_FILE
        values = extract_table(rom, cpu_addr, n_entries)
        tables_data[name] = values
        print(f"  {name:20s}  cpu=${cpu_addr:08X}  file=0x{file_off:06X}  "
              f"{n_entries} entries  [{min(values):6d} .. {max(values):6d}]")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)

    with open(OUT_PATH, "w") as f:
        f.write(emit_c(tables_data))
    print(f"Wrote: {OUT_PATH}")

    with open(HDR_PATH, "w") as f:
        f.write(emit_h(tables_data))
    print(f"Wrote: {HDR_PATH}")

if __name__ == "__main__":
    main()
