#!/usr/bin/env python3
"""
extract_track.py — VRD 32X track data extractor.

Reads curvature tables for all 3 tracks from the ROM and integrates them into
world-space waypoints. Outputs C source + header files for the Saturn port.

Address mapping: 68K CPU address → file offset = cpu_addr - 0x800000

Track curvature table CPU addresses (from road_segment_ptr_table at $00930612):
  Track 0: 0x0093061E  (file 0x13061E) — Beginner
  Track 1: 0x0093261E  (file 0x13261E) — Medium   (closes within ~3 world units)
  Track 2: 0x0093461E  (file 0x13461E) — Expert   (identical data to track 1)

Curvature block layout per track: 4 pages × 0x800 bytes = 0x2000 bytes
  Each page: 1024 signed byte pairs
  Page 0 byte 0 (h_curv):  horizontal curvature, 512-step angle units
  Page 0 byte 1 (v_curv):  vertical curvature / banking angle
  Pages 1-3: normal, gradient, and auxiliary data (extracted but not used here)

Integration (horizontal):
  heading = (heading + h_curv[i]) & 511   (wraps 0..511)
  world_x += sin(heading * 2π/512) * TRACK_STEP
  world_z += cos(heading * 2π/512) * TRACK_STEP
"""

import sys, os, math, struct

ROM      = os.path.join(os.path.dirname(__file__), '..', 'build', 'vr_rebuild.32x')
STEP     = 10      # world units per segment
N_SEGS   = 1024

OUT_C    = os.path.join(os.path.dirname(__file__), '..', 'saturn', 'src', 'render', 'track_data.c')
OUT_H    = os.path.join(os.path.dirname(__file__), '..', 'saturn', 'src', 'render', 'track_data.h')

# Track curvature table CPU addresses; file_offset = cpu - 0x800000
TRACK_CPU_ADDRS = [0x0093061E, 0x0093261E, 0x0093461E]
TRACK_NAMES     = ['track_0', 'track_1', 'track_2']


def signed8(b):
    return b if b < 128 else b - 256


def extract_track(rom_data, cpu_addr):
    """Extract waypoints from a curvature table at the given CPU address."""
    off = cpu_addr - 0x800000
    page0 = rom_data[off : off + 0x800]

    h_curv = [signed8(page0[i * 2])     for i in range(N_SEGS)]
    v_curv = [signed8(page0[i * 2 + 1]) for i in range(N_SEGS)]

    # Integrate heading and position
    heading = 0
    x, z = 0.0, 0.0
    waypoints = []
    for i in range(N_SEGS):
        waypoints.append((round(x), round(z), heading, h_curv[i], v_curv[i]))
        ang = heading * 2.0 * math.pi / 512
        x  += math.sin(ang) * STEP
        z  += math.cos(ang) * STEP
        heading = (heading + h_curv[i]) & 511

    xs = [w[0] for w in waypoints]
    zs = [w[1] for w in waypoints]
    closure = (round(x) - waypoints[0][0], round(z) - waypoints[0][1])
    return waypoints, xs, zs, closure


def main():
    with open(ROM, 'rb') as f:
        rom = f.read()

    all_tracks = []
    for i, cpu in enumerate(TRACK_CPU_ADDRS):
        wp, xs, zs, closure = extract_track(rom, cpu)
        print(f'Track {i} (CPU 0x{cpu:08X}):')
        print(f'  x: {min(xs)} to {max(xs)}  (range {max(xs)-min(xs)})')
        print(f'  z: {min(zs)} to {max(zs)}  (range {max(zs)-min(zs)})')
        print(f'  closure gap: {closure}')
        all_tracks.append(wp)

    # Write header
    with open(OUT_H, 'w') as f:
        f.write('/* render/track_data.h — VRD track data, auto-generated by tools/extract_track.py\n')
        f.write(' * DO NOT EDIT — regenerate with: python3 tools/extract_track.py\n')
        f.write(' */\n')
        f.write('#pragma once\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'#define TRACK_N_SEGS  {N_SEGS}  /* segments per lap */\n')
        f.write(f'#define TRACK_STEP     {STEP}  /* world units per segment */\n')
        f.write( '#define TRACK_ROAD_HW 110  /* road half-width, world units */\n')
        f.write(f'#define TRACK_COUNT     {len(TRACK_CPU_ADDRS)}  /* number of tracks */\n\n')
        f.write('/* One track segment: centerline position, heading, and curvature. */\n')
        f.write('typedef struct {\n')
        f.write('    int16_t  x;       /* centerline x, world units */\n')
        f.write('    int16_t  z;       /* centerline z, world units */\n')
        f.write('    uint16_t heading; /* road heading, 512-step units (0=+Z, 128=+X) */\n')
        f.write('    int8_t   h_curv;  /* horizontal curvature (signed, heading delta/seg) */\n')
        f.write('    int8_t   v_curv;  /* vertical curvature / banking (signed) */\n')
        f.write('} track_seg_t;\n\n')
        for name in TRACK_NAMES:
            f.write(f'extern const track_seg_t {name}[TRACK_N_SEGS];\n')
        f.write('\nextern const track_seg_t * const tracks[TRACK_COUNT];\n')
        f.write('\n/* Active track — defaults to track_1. Reassign to switch tracks. */\n')
        f.write('extern const track_seg_t *track_segs;\n')

    # Write C source
    with open(OUT_C, 'w') as f:
        f.write('/* render/track_data.c — VRD track data, auto-generated by tools/extract_track.py\n')
        f.write(' * DO NOT EDIT — regenerate with: python3 tools/extract_track.py\n')
        f.write(' */\n')
        f.write('#include "track_data.h"\n\n')

        for i, (name, waypoints) in enumerate(zip(TRACK_NAMES, all_tracks)):
            cpu = TRACK_CPU_ADDRS[i]
            f.write(f'/* Track {i} — CPU 0x{cpu:08X} */\n')
            f.write(f'const track_seg_t {name}[TRACK_N_SEGS] = {{\n')
            for j, (wx, wz, wh, hc, vc) in enumerate(waypoints):
                comma = ',' if j < N_SEGS - 1 else ' '
                f.write(f'    {{{wx:6d},{wz:6d},{wh:3d},{hc:4d},{vc:4d}}}{comma}\n')
            f.write('};\n\n')

        f.write('const track_seg_t * const tracks[TRACK_COUNT] = {\n')
        for name in TRACK_NAMES:
            f.write(f'    {name},\n')
        f.write('};\n\n')
        f.write('/* Active track pointer — defaults to track_1. */\n')
        f.write('const track_seg_t *track_segs = track_1;\n')

    print(f'\nWrote {OUT_C}')
    print(f'Wrote {OUT_H}')


if __name__ == '__main__':
    main()
